/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoulder.gltf
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Shoulder(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/shoulder.gltf')
  const { actions } = useAnimations(animations, group)

  const startingPosition = [0, 0, 0];

  useEffect(() => {
    if (group.current) {
      group.current.position.set(...startingPosition);
    }
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh 
            name="Bones_Layed_out001" 
            geometry={nodes.Bones_Layed_out001.geometry} 
            material={materials['initialShadingGroup.001']} 
            rotation={[Math.PI / 2, 0, 0]} 
            
        />
      </group>
    </group>
  )
}

useGLTF.preload('/shoulder.gltf')
export default () => (
  <Shoulder/>
)
